import Head from "next/head";
import Image from "next/image";
import styled from "styled-components";

const Text = styled.p`
  color: red;
`;

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Text>Hid </Text>
    </div>
  );
}
